### PR TITLE
Show breaking news whenever

### PR DESCRIPTION
**Pull request by NathanielBennett**
Show the "Breaking news" kicker, even when kickers are surpressed.

@janua What do you think?

### CODE REVIEW

**Comment by janua** [comment]
[Tests?](https://github.com/guardian/facia-scala-client/blob/master/fapi-client/src/test/scala/com/gu/facia/api/utils/ItemKickerTest.scala)

**Comment by NathanielBennett** [comment]
Point taken

**Comment by NathanielBennett** [comment]
Hows that, @janua

**Comment by janua** [comment]
:+1:

**Pull request merged**
