### PR TITLE
Add notes on building a release

### PR DESCRIPTION
**Pull request by kelvin-chappell**

### CODE REVIEW

**Comment by davidfurey** [comment]
Very helpful, but maybe add a link to https://docs.google.com/document/d/1M_MiE8qntdDn97QIRnIUci5wdVQ8_defCqpeAwoKY8g/edit#heading=h.r815791vmxv5 ?

**Comment by janua** [comment]
Yes the document is very handy!

**Comment by kelvin-chappell** [comment]
@davidfurey I was thinking of adding a link to the doc but I get paranoid about public repos.  Now you've made a precedent I will add it.

**Comment by davidfurey** [comment]
Glad I could help :-) There are no secrets in that doc anyway as far as I can see.

**Comment by kelvin-chappell** [comment]
No, it's not a rational paranoia.

**Pull request merged**
