### PR TITLE
Add published by to trail

### PR DESCRIPTION
**Pull request by Reettaphant**
Adds a publishedBy property to Trail.

### CODE REVIEW

**Comment by Reettaphant** [comment]
@janua @piuccio

**Comment by piuccio** [comment]
looks good

**Comment by janua** [comment]
Looks good :+1:
We should run this through frontend after it gets merged to ensure there are no problems.
I am happy to bump it for you. Are you going to merge today?

**Comment by Reettaphant** [comment]
@janua  Yes, if you have time to do it today.

**Comment by Reettaphant** [comment]
I have now added publishedBy to supporting items as well.

**Comment by janua** [comment]
Great! Did you test this and it worked as expected?
If there are no tests around it in scala it might be worth writing tests for it for the JSON parsing.
:+1:

**Comment by Reettaphant** [comment]
It works. I can write tests for it if you can tell me where the tests for the JSON parsing are.

**Comment by janua** [comment]
@Reettaphant There are some here https://github.com/guardian/facia-scala-client/blob/master/facia-json/src/test/scala/com/gu/facia/client/models/CollectionSpec.scala

**Comment by Reettaphant** [comment]
@janua I've now updated the test on supporting items. Is that the addition that you wanted?

**Comment by janua** [comment]
@Reettaphant Looks good! :+1:
Shall I merge it?

**Comment by Reettaphant** [comment]
@janua Yes!

**Pull request merged**
